String print_page(String city, String countrycode, String apikey) {
  write_header("web_page()");
  String webpage = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\n"
"    <meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />"
"    <meta http-equiv=\"Pragma\" content=\"no-cache\" />"
"    <meta http-equiv=\"Expires\" content=\"0\" />"
"    <title>Options</title>\n"
"    <style>\n"
"      .c{text-align: center;} \n"
"      div,input{padding:5px;font-size:1em;}\n"
"      input{width:50%;} \n"
"      body{text-align: center;font-family:verdana;} \n"
"      button{border:0;border-radius:0.3rem;background-color:#1fa3ec;color:#fff;line-height:2.4rem;font-size:1.2rem;width:50%;}\n"
"    </style>\n"
"  <body>\n"
"    <div align=\"center\" style=\"text-align:left;display:inline-block;min-width:260px;\">\n"
"      <h1>ESP8266 Weather Station Configuration Page</h1>\n"
"      <form action=\"/submit.php\" method=\"GET\" align=\"center\">\n"
"        <h3>City</h3>\n"
"        <input type=\"text\" name=\"city\" value=\"" + city + "\"><br><br>\n"
"        <h3>Country code</h3>\n"
"        <input type=\"text\" name=\"countrycode\" value=\"" + countrycode + "\"><br><br>\n"
"        <h3>OpenWeatherMap API Key</h3>\n"
"        <input type=\"text\" name=\"apikey\" value=\"" + apikey + "\"><br><br>\n"
"        <button>Submit</button>\n"
"      </form>\n"
"    </div>\n"
"  </body>\n"
"</html>\n";
  return webpage;
}
